name: g-ftp
version: '0.1' 
summary: gftp
description: |
  This is gftp snap application

grade: stable
confinement: devmode

apps:
  g-ftp:
    command: desktop-launch $SNAP/usr/bin/gftp-gtk
    plugs:
      - network
      - unity7
      - x11
      - home
      - opengl
      - pulseaudio

parts:
  app:
    plugin: nil
    stage-packages:
      - gftp
      - overlay-scrollbar-gtk2
      - libgail-3-0
      - libatk-bridge2.0-0
      - libatk-adaptor
      - unity-gtk2-module:amd64
      - libcanberra-gtk-module:amd64
      - fonts-wqy-zenhei
    stage:
      - -usr/sbin/update-icon-caches
    after: [desktop-gtk2]
